server:
  port: 8080

module-processor:
  output-dir: output
  default-module-name: unknown-module
  default-replace-mode: NONE
  default-mock-id-prefix: MOCK
  default-min-outline-depth: 2
  default-require-keyword: false
  default-include-sub-items: false
  level-two-min-text-length: 80
  title-max-length: 80
  csv-with-bom: true

polarion:
  base-url: "http://alm.freetech.com"
  module-file-name: "module.xml"
  default-project-id: "FDP_Demo"
  default-module-folder: "10 Stakeholder Requirement"
  default-work-item-type: "stakeholderrequirement"
  auth:
    type: "NONE"
    cookie: ""
    username: ""
    password: ""
    token: ""
  svn:
    executable: "svn"
    username: "polarion"
    password: "uaorar"
    checkout-timeout-seconds: 60
    update-timeout-seconds: 60
    commit-timeout-seconds: 60
    default-commit-message: "update module.xml"
    cleanup-temp-dir: true
    cleanup-commit-workspace: false
  work-item-api:
    enabled: true
    create-url: "http://10.179.60.154:30000/workitem/ws/create"
    default-polarion-id: "FDP_Demo"
    default-type: "stakeholderrequirement"
    default-author-id: "pingping.xu"
    connect-timeout-ms: 5000
    read-timeout-ms: 30000
    default-custom-fields: []
    project-custom-fields:
      RMT_Platform:
        - id: "requirementsource"
          multi: false
          type: "EnumOptionId"
          enum-options:
            - id: "internal"
              name: "Internal内部的需求"
            - id: "external"
              name: "External来自外部的需求"
            - id: "Regulation"
              name: "Regulation法规需求"
        - id: "reqType"
          multi: false
          type: "EnumOptionId"
          enum-options:
            - id: "functional"
              name: "Functional Requirement 功能需求"
            - id: "nofunctional"
              name: "Non-Functional Requirement 非功能需求(性能等)"
            - id: "interface"
              name: "Interface Requirement 接口需求"
            - id: "constraint"
              name: "Constraint 约束条件"
            - id: "information"
              name: "Information 信息类需求"
        - id: "verificationcriteria"
          multi: false
          type: "text/html"
      RMT_Platfrom_Demo:
        - id: "requirementsource"
          multi: false
          type: "EnumOptionId"
          enum-options:
            - id: "internal"
              name: "Internal内部的需求"
            - id: "external"
              name: "External来自外部的需求"
            - id: "Regulation"
              name: "Regulation法规需求"
        - id: "reqType"
          multi: false
          type: "EnumOptionId"
          enum-options:
            - id: "functional"
              name: "Functional Requirement 功能需求"
            - id: "nofunctional"
              name: "Non-Functional Requirement 非功能需求(性能等)"
            - id: "interface"
              name: "Interface Requirement 接口需求"
            - id: "constraint"
              name: "Constraint 约束条件"
            - id: "information"
              name: "Information 信息类需求"
        - id: "verificationcriteria"
          multi: false
          type: "text/html"
    auth-type: "NONE"
    token: ""
