server:
  port: 8080

module-processor:
  output-dir: output
  default-module-name: unknown-module
  default-replace-mode: NONE
  default-mock-id-prefix: MOCK
  default-min-outline-depth: 2
  default-require-keyword: false
  default-include-sub-items: false
  level-two-min-text-length: 80
  title-max-length: 80
  csv-with-bom: true

polarion:
  base-url: "http://alm.freetech.com"
  module-file-name: "module.xml"
  default-project-id: "FDP_Demo"
  default-module-folder: "10 Stakeholder Requirement"
  default-work-item-type: "stakeholderrequirement"
  auth:
    type: "NONE"
    cookie: ""
    username: ""
    password: ""
    token: ""
  svn:
    executable: "svn"
    username: "polarion"
    password: "uaorar"
    checkout-timeout-seconds: 60
    update-timeout-seconds: 60
    cleanup-temp-dir: true
  work-item-api:
    enabled: true
    create-url: "http://10.179.60.154:30000/workitem/ws/create"
    default-polarion-id: "FDP_Demo"
    default-type: "stakeholderrequirement"
    default-author-id: "pingping.xu"
    connect-timeout-ms: 5000
    read-timeout-ms: 30000
    default-custom-fields:
      - id: "requirementsource"
        multi: false
        type: "EnumOptionId"
        value: "Regulation"
    auth-type: "NONE"
    token: ""
